import type { Metadata } from "next";
import { Inter, Geist_Mono, Allura, DM_Mono } from "next/font/google";
import "./globals.css";
import BackgroundStyle from "@/components/apps/BackgroundStyle";

const dm_mono = DM_Mono({
  variable: "--font-dm-mono",
  subsets: ["latin"],
  weight: ["400"],
});

const allura = Allura({
  variable: "--font-allura",
  subsets: ["latin"],
  weight: ["400"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${geistMono.variable} ${allura.variable} ${dm_mono.variable} ${inter.className} antialiased`}
      >
        <BackgroundStyle type="dotted">{children}</BackgroundStyle>
        <div id="modal-root"></div>
      </body>
    </html>
  );
}
